package bdpaquiz.andersen.stanford.bdpamilwaukeequiz;

/**
 * Created by Stan on 8/13/2014.
 */

import java.util.*;

public class LoadGameQuestion {

    public static void main(String[] args){}
    public static ArrayList<Chapter> loadChapters(){
        ArrayList<Chapter> $allChapters = new ArrayList<Chapter>();
        Chapter $tempChapter=new Chapter();
        ArrayList<String> $options=new ArrayList<String>();
        $tempChapter=new Chapter("Chapter 5_ Java");
        $options= new ArrayList<String>();
        $options.add(" char ");
        $options.add(" double ");
        $options.add(" boolean ");
        $tempChapter.addQuestion(new Question(" Java has primitive types of variables. Which one of the following is not a primitive declaration in Java? ", " int[] ", " Their are three types of primitive variables. 1) integral types such as integers (int) and characters (chars) 2) floating point types such as fraction numbers (doubles) and 3) boolean types such as true or false ", false, $options));
        $options= new ArrayList<String>();
        $options.add(" static ");
        $options.add(" main ");
        $options.add(" void ");
        $options.add(" String[] args ");
        $tempChapter.addQuestion(new Question(" In Java after the class declaration, a method may may be declared as follows: â€œpublic static void main(String[] args){â€œ. What is the visibility ", " public ", " Visibility describes who can run the program so a public visibility means any one can run this. ", false, $options));
        $options= new ArrayList<String>();
        $options.add(" 0 ");
        $options.add(" 2 ");
        $options.add(" as many as desired ");
        $tempChapter.addQuestion(new Question("  In Java after the class declaration, a method may may be declared as follows: â€œpublic static void main(String[] args){â€œ. How many main methods may this class have? ", " 1 ", " it is one because of the static declaration meaning this is a class method. ", false, $options));
        $options= new ArrayList<String>();
        $options.add(" public ");
        $options.add(" static ");
        $options.add(" void ");
        $options.add(" String[] args ");
        $tempChapter.addQuestion(new Question(" In Java after the class declaration, a method may may be declared as follows: â€œpublic static void main(String[] args){â€œ. What allows the JVM (Java Virtual machine) to know where to starrt? ", " main ", " This is a main method so the JVM will know to start with this method ", false, $options));
        $options= new ArrayList<String>();
        $options.add(" public ");
        $options.add(" static ");
        $options.add(" main ");
        $options.add(" String[] args ");
        $tempChapter.addQuestion(new Question(" In Java after the class declaration, a method may may be declared as follows: â€œpublic static void main(String[] args){â€œ. What is the return ", " void ", " A return of void means that there will be no returned value but it must still be declared so java can properly compile. ", false, $options));
        $options= new ArrayList<String>();
        $options.add(" false ");
        $tempChapter.addQuestion(new Question(" In Java the following will will result in true (the other option being it will crash or be false) assuming x is an integer already initialized :   !(x++ == x +1) || true && false; ", " true ", " the or operation (x++==x+1) is false because even though x++ is an incrementor when the ++ is after the variable it only takes", false, $options));
        $options= new ArrayList<String>();
        $options.add(" integrated design environment ");
        $options.add(" internal design environment ");
        $options.add(" internal development environment ");
        $tempChapter.addQuestion(new Question(" What is an IDE. ", " integrated development environment ", " An IDE or integrated development environment such as eclipse for Java can be excellent for debugging and help with syntax errors. Also more complex editors such as C++ can help catch syntax editors. ", true, $options));
        $options= new ArrayList<String>();
        $options.add(" primitive type ");
        $options.add(" interface ");
        $options.add(" exception ");
        $tempChapter.addQuestion(new Question(" An object orientated language allows to define a new class which can be considered to be a new... ", "  data element ", " This is the object in object orientated programming. ", true, $options));
        $options= new ArrayList<String>();
        $options.add(" new char[15]; ");
        $options.add(" {[5]; ");
        $options.add(" new int{15}; ");
        $tempChapter.addQuestion(new Question(" In Java to form an array the code to form an array with 15 items would be int[] x= â€¦ ", " new int[15]; ", " the new int[15] will form and int[] as int[] x must be an integer array and it will be 15 units long. It will form an integer array all with fifteen integers items all initialized to the default (0). ", true, $options));
        $allChapters.add($tempChapter);
        $tempChapter=new Chapter("chapter 7");
        $options= new ArrayList<String>();
        $options.add("2 ");
        $options.add("10 ");
        $options.add("5 ");
        $options.add("8 ");
        $tempChapter.addQuestion(new Question("The ISO OSI has how many layers? ", "7 ", "Physical, Data Link, Network, Transport, Session, Presentation, Application", false, $options));
        $options= new ArrayList<String>();
        $options.add("2 ");
        $options.add("3 ");
        $options.add("5 ");
        $options.add("6 ");
        $tempChapter.addQuestion(new Question("The internet model contains how many layers? ", "4 ", "subnet(data link), internet(network), end to end(transport), application", false, $options));
        $options= new ArrayList<String>();
        $options.add("True ");
        $tempChapter.addQuestion(new Question("When using HTML if one does not close a header the browser will crash? ", "False ", "With HTML the browser will display what it can and not crash or display cryptic error messages.", false, $options));
        $options= new ArrayList<String>();
        $options.add("64 ");
        $options.add("16 ");
        $options.add("8 ");
        $options.add("4 ");
        $tempChapter.addQuestion(new Question("How many bits is IPv4? ", "32 ", "IPv6 is 64 bits while version 4 is 32 bits", false, $options));
        $options= new ArrayList<String>();
        $options.add("error checking ");
        $options.add("message relaying protocol ");
        $options.add("interconnectivity ");
        $options.add("WAN");
        $tempChapter.addQuestion(new Question("The physical layer of the ISO OSI does which of the following? ", "Connects two points ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("medium to connect to points ");
        $options.add("OSI ");
        $options.add("instant messaging ");
        $options.add("TCP/IP");
        $tempChapter.addQuestion(new Question(" The data link layer of the ISO OSI does which of the following? ", "provides structure to message and error checking ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("higher level language ");
        $options.add("end-to-end connection ");
        $options.add("wireless connectivity ");
        $options.add("IP address");
        $tempChapter.addQuestion(new Question(" The networking layer of the ISO OSI is which of the following? ", "lowest layer of networking protocol for exchanging messages via relaying messages between intervening computers. ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("uses a BUS to connect multiple computers ");
        $options.add("CSMA/CD ");
        $options.add("is the medium of communication ");
        $options.add("prints message to screen");
        $tempChapter.addQuestion(new Question(" The transport layer of the ISO OSI does which of the following? ", "receiver gets all frames, in the correct order, and without duplication ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("session layer ");
        $options.add("presentation layer ");
        $options.add("application layer");
        $tempChapter.addQuestion(new Question("The internet model contains all the following from the ISO OSI except _____ in the application layer. ", "transport layer ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("transport ");
        $options.add("network ");
        $options.add("application ");
        $options.add("End-to-end");
        $tempChapter.addQuestion(new Question("The internet model’s subnet(data link) layer contains the ISO OSI data link and ____ layer? ", "physical ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("CSMA/CA ");
        $options.add("IEEE standard 802.11 ");
        $options.add("fiber optic cable ");
        $options.add("HTTP ");
        $tempChapter.addQuestion(new Question(" Ethernet protocol uses___? ", "CSMA/CD ", " IEEE standard 802.3  (carrier sense multiple access/collision detection)", false, $options));
        $options= new ArrayList<String>();
        $options.add("CSMA/CD ");
        $options.add("IEEE standard 802.3 ");
        $options.add("fiber optic cable ");
        $options.add("BUS ");
        $tempChapter.addQuestion(new Question("Wi-Fi uses _____. ", "CSMA/CA ", "IEEE standard 802.11 (carrier sense multiple access/collision avoidance)", false, $options));
        $options= new ArrayList<String>();
        $options.add("1972 ");
        $options.add("1973 ");
        $options.add("1974 ");
        $options.add("1979");
        $tempChapter.addQuestion(new Question("When did ARPAnet begin? ", "late 1960’s ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("1980 ");
        $options.add("1968 ");
        $options.add("1973 ");
        $options.add("1990");
        $tempChapter.addQuestion(new Question("When was the first email sent? ", "1971 ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("1971 ");
        $options.add("late 1960’s ");
        $options.add("1989 ");
        $options.add("1992");
        $tempChapter.addQuestion(new Question("When did TCP/IP protocols become standard? ", "1983 ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("Localized Area Nuisances ");
        $options.add("Limited Area Network ");
        $options.add("Low Aerial Net ");
        $options.add("Local Area News");
        $tempChapter.addQuestion(new Question("LAN stands for? ", "Local Area Network ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("World Area Network ");
        $options.add("World Area News ");
        $options.add("Wide Awake News ");
        $options.add("Weak Area Network");
        $tempChapter.addQuestion(new Question("WAN stands for? ", "Wide Area Network ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("Inside System Operations Operating System Internals ");
        $options.add("Initial System Operations Opposing Systems Interconnectivity ");
        $options.add("International Systems Organization Operating Systems Intranetwork ");
        $options.add("Internal System Online Organizational Systems Inside");
        $tempChapter.addQuestion(new Question("ISO OSI stands for? ", "International Standards Organization Open Systems Interconnection ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("automatic power installation ");
        $options.add("automatic program installation ");
        $options.add("applicable privacy investigation ");
        $options.add("arranged personal information");
        $tempChapter.addQuestion(new Question("What does API stand for? ", "application program interface ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("international service provider ");
        $options.add("internet security protocol ");
        $options.add("initial security personal ");
        $options.add("internal security program");
        $tempChapter.addQuestion(new Question("What does ISP stand for? ", "internet service provider ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("initial protocol ");
        $options.add("intermediate position ");
        $options.add("immediate persecution ");
        $options.add("individual property");
        $tempChapter.addQuestion(new Question("What does IP stand for? ", "internet protocol ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("travel continuity protocol ");
        $options.add("time control protocol ");
        $options.add("transitional continuity position ");
        $options.add("travel control personal");
        $tempChapter.addQuestion(new Question("TCP stands for? ", "transaction control protocol ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("real time simulation ");
        $options.add("regular timed solution ");
        $options.add("required time situation ");
        $options.add("relationship transform standard");
        $tempChapter.addQuestion(new Question("RTS stands for? ", "request to send ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("click to send ");
        $options.add("click to sell ");
        $options.add("clear timed standard ");
        $options.add("computational technology security");
        $tempChapter.addQuestion(new Question("CTS stands for? ", "clear to send ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("world wide win ");
        $options.add("win win win ");
        $options.add("wide world win ");
        $options.add("window washer widow");
        $tempChapter.addQuestion(new Question("www stands for? ", "world wide web ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("hypertext transport procedure ");
        $options.add("hyperlink text protocol ");
        $options.add("hyperlink text transport procedure ");
        $options.add("hyperlink transport text protocol");
        $tempChapter.addQuestion(new Question("http stands for? ", "hypertext transport protocol ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("initial state numbers ");
        $options.add("initial security numbers ");
        $options.add("intentional security nuisances ");
        $options.add("international secure network");
        $tempChapter.addQuestion(new Question("ISNs stands for? ", "initial sequence numbers ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("apparent programmable interface ");
        $options.add("arranged programmable interface ");
        $options.add("applied powerful internet ");
        $options.add("arranged plausible intranet");
        $tempChapter.addQuestion(new Question("API stands for? ", "application program interface ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("unilateral resource locator ");
        $options.add("uniform resource liability ");
        $options.add("ultimate resource locator ");
        $options.add("underrated locale");
        $tempChapter.addQuestion(new Question("URL stands for? ", "uniform resource locator ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("hyperlink text malleable linguistics ");
        $options.add("hypertext management language ");
        $options.add("hyperlink timed merge language ");
        $options.add("hypertext modified location");
        $tempChapter.addQuestion(new Question("HTML stands for? ", "hypertext markup language ", "", true, $options));
        $allChapters.add($tempChapter);
        $tempChapter=new Chapter("chapter 8");
        $options= new ArrayList<String>();
        $options.add("random ");
        $options.add("broadband ");
        $options.add("linear ");
        $options.add("batch");
        $tempChapter.addQuestion(new Question("Two early types of databases were hierarchal and ___? ", "networking ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("1971 ");
        $options.add("1980’s ");
        $options.add("1975 ");
        $options.add("late 1950’s");
        $tempChapter.addQuestion(new Question("when where databases started? ", "late 1960’s ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("space ");
        $options.add("location ");
        $options.add("organization");
        $tempChapter.addQuestion(new Question("The biggest advantage of using a database? ", "speed ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("instances ");
        $options.add("symbols ");
        $options.add("connections ");
        $options.add("status");
        $tempChapter.addQuestion(new Question("The marks at the ends of lines on an E-R(entity relationship) diagram represent? ", "cardinalities ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("internal ");
        $options.add("external ");
        $options.add("conceptual");
        $tempChapter.addQuestion(new Question("Which is not a schema a database developer would not refer to? ", "interconnectivity ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add("key data ");
        $options.add("primary key ");
        $options.add("memory location ");
        $options.add("stack pointer");
        $tempChapter.addQuestion(new Question("What is metadata? ", "data about data ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("data byte management status ");
        $options.add("database management status ");
        $options.add("data binomial mass standard ");
        $options.add("databyte management status");
        $tempChapter.addQuestion(new Question("What does DBMS mean? ", "database management system ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("field ");
        $options.add("unique characteristic ");
        $options.add("column ");
        $options.add("memory location");
        $tempChapter.addQuestion(new Question("A tuple is a/n ", "row relationship ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("row ");
        $options.add("column ");
        $options.add("unique identifier ");
        $options.add("relation");
        $tempChapter.addQuestion(new Question("A field is a/n ", "attribute ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("relationship ");
        $options.add("row ");
        $options.add("primary key ");
        $options.add("database");
        $tempChapter.addQuestion(new Question("A relation is a ", "table ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("ambiguous ");
        $options.add("detailed ");
        $options.add("broad ");
        $options.add("numbers");
        $tempChapter.addQuestion(new Question("Primary keys are ", "unique ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add("alphanumeric ");
        $options.add("based of other data ");
        $options.add("letters ");
        $options.add("metadata");
        $tempChapter.addQuestion(new Question("Surrogate keys are ", "numbers ", "", true, $options));
        $allChapters.add($tempChapter);
        $tempChapter=new Chapter("Chapter 9_ Ethics");
        $options= new ArrayList<String>();
        $options.add(" trademarks ");
        $options.add(" trade secrets ");
        $options.add(" patents ");
        $options.add(" copyrights ");
        $tempChapter.addQuestion(new Question(" What is NOT a way to protect intellectual property. ", " encryption ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add(" encryption ");
        $options.add(" trademarks ");
        $options.add(" patents ");
        $options.add(" copyrights ");
        $tempChapter.addQuestion(new Question(" Object code is used to protected and related to? ", " trade secrets ", " It is way to keep the code a trade secret ", false, $options));
        $options= new ArrayList<String>();
        $options.add(" 10 ");
        $options.add(" 100 ");
        $options.add(" 50 ");
        $options.add(" 25 ");
        $tempChapter.addQuestion(new Question(" How many years do patents last ", " 20 ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add(" encryption ");
        $options.add(" trademarks ");
        $options.add(" trade secrets ");
        $options.add(" patents ");
        $tempChapter.addQuestion(new Question(" Open source in contrast to what? ", " copyrights ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add(" true ");
        $tempChapter.addQuestion(new Question(" Privacy over the Internet is well protectect. ", " false ", "", false, $options));
        $options= new ArrayList<String>();
        $options.add(" encryption ");
        $options.add(" trade secrets ");
        $options.add(" patents ");
        $options.add(" copyrights ");
        $tempChapter.addQuestion(new Question(" What does genericide destroy? ", " trademarks ", " Genericide is when a word becomes part of common speech which cannot be trademarked. ", true, $options));
        $options= new ArrayList<String>();
        $options.add(" Trojan ");
        $options.add(" worm ");
        $tempChapter.addQuestion(new Question(" A (bad) program that is concealed in another? ", " Viruses ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add(" Viruses ");
        $options.add(" worm ");
        $tempChapter.addQuestion(new Question(" A (bad) program with a second function ", " Trojan ", "", true, $options));
        $options= new ArrayList<String>();
        $options.add(" Viruses ");
        $options.add(" Trojan ");
        $tempChapter.addQuestion(new Question(" A program that travels through the network exploiting security weaknesses. ", " worm   ", "", true, $options));
        $allChapters.add($tempChapter);
        return $allChapters;
    }
}

